version: '3.8'

services:
  couchdb:
    image: my-couchdb-app
    build:
      context: ./Couch-DB/ContainerImage
      dockerfile: Dockerfile
    ports:
      - "5984:5984"
    container_name: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=student
    networks:
      - mynetwork

  fastapi:
    image: my-fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: fastapi
    environment: # Setze Umgebungsvariablen für die FastAPI-App außerhalb des Containers, um die 12-Faktor-App-Prinzipien zu erfüllen
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=5984
      - COUCHDB_USERNAME=admin
      - COUCHDB_PASSWORD=student

    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
