apiVersion: v1                 # API-Version des Objekts (v1 für Kubernetes API-Version 1)
kind: Secret                   # Art des Objekts (Secret)
metadata:                      # Metadaten des Objekts
  name: fastapi-k8-secret      # Name des Secrets
type: Opaque                   # Typ des Secrets (Opaque bedeutet, dass die Daten als undurchsichtig behandelt werden)
data:                          # Datenbereich, der die verschlüsselten Daten enthält
  COUCHDB_USERNAME: YWRtaW4=  # Base64-kodierte Version des Benutzernamens "admin"
  COUCHDB_PASSWORD: c3R1ZGVudA==  # Base64-kodierte Version des Passworts "student"
