apiVersion: v1
kind: Secret
metadata:
  name: fastapi-k8-secret
type: Opaque
data:
  COUCHDB_USERNAME: YWRtaW4=  # base64 encoded value of "admin"
  COUCHDB_PASSWORD: c3R1ZGVudA== # base64 encoded value of "student"
