apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-k8-configmap
  labels:
    app: fastapi-k8
data:
  COUCHDB_URL: "http://couchdb-k8-service:5984"
  COUCHDB_HOST: "couchdb"
  COUCHDB_PORT: "5984"
